language: go

go:
  - 1.11.1

before_install:
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- go get github.com/onsi/ginkgo/ginkgo
- export PATH=$PATH:$GOPATH/bin
- export CGO_LDFLAGS_ALLOW='-msse2,-mavx'
- export CGO_CFLAGS_ALLOW='-msse2,-mavx'
- gometalinter --install --update

script:
- travis_wait 30 ginkgo -tags="pow_avx pow_sse pow_c pow_c128" -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress

after_success:
- gometalinter -e bindata --deadline=1000s ./...
- goveralls -coverprofile=coverage.out -service=travis-ci

